### ISSUE TITLE
Need help for inference

### ISSUE THREAD

**Issue by Josh-Yang95** [XavierXiao/Dreambooth-Stable-Diffusion#23]
![Screenshot from 2022-09-21 23-26-27](https://user-images.githubusercontent.com/70742598/191531438-efb4536a-b6d6-43ec-88b9-64a8211a7f49.png)

Hi, thanks for Dreambooth implementation. It's amazing.

The issue I suffered was as follows.

I trained the model with my data and wanted to generate some images. 

But the above error occurred when generating. 

I used the same code in this repo and didn't fix anything.

Then, what should I do about this issue..

**Comment by XavierXiao** [comment]
You can just run `pip install -e .` This is because your earlier ldm environment has some conflict.

**Comment by Josh-Yang95** [comment]
Thanks for the quick response. 

I tried your direction, but it didn't work.

So I cloned your repo again and reset the environment. 

Finally, this way solved the issue, thanks.
