### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by alienhd** [XavierXiao/Dreambooth-Stable-Diffusion#24]
What should i do?

```
Traceback (most recent call last):
  File "main.py", line 787, in <module>
    ngpu = len(lightning_config.trainer.gpus.strip(",").split(','))
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by csyxwei** [comment]
Maybe you can try to use `--gpus 0, ` instead of `--gpus 0`.

**Comment by alienhd** [comment]
Oh thank you very much that worked but sadly i ran into the next error:
`AttributeError: module 'signal' has no attribute 'SIGUSR1'`
as far as i understand this could be related to me using windows instead of Unix.

**Comment by csyxwei** [comment]
You can refer to this [textual_inversion issue 80](https://github.com/rinongal/textual_inversion/issues/80) to find some solutions.

**Comment by alienhd** [comment]
Ok thanks, have a nice day.

**Comment by bh-github-learn** [comment]
You could only add
lightning_config.trainer.gpus = str (lightning_config.trainer.gpus)
before
ngpu = len(lightning_config.trainer.gpus.strip(",").split(','))
and its solved
