### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by spinferno** [XavierXiao/Dreambooth-Stable-Diffusion#38]
Hey I am running on PC via Anaconda CLI with Administrator privileges.
I'm getting this error thrown: "PermissionError: [WinError 5] Access is denied", which cascades with more "MemoryError" errors.

How may I get it to work?

This is the command I am using:
`python main.py --base configs/stable-diffusion/v1-finetune_unfrozen.yaml -t --actual_resume models/ldm/stable-diffusion-v1/sd-v1-4-full-ema.ckpt -n spinferno_01 --gpus 0, --data_root training-images --reg_data_root regularization-images --class_word man`

and this is the full exception traceback:
[exception traceback.txt](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/files/9651489/exception.traceback.txt)

My deepest thanks in advance for anyone who can take a look and get this working :)

**Comment by TemporalLabsLLC-SOL** [comment]
Are you running in administrator mode?

**Comment by spinferno** [comment]
I eventually got it to work but can't for the life of me recall how I fixed the issue, there's been so many local installs released in the last week it's fried my brain. If I remember I will post it here but please don't spend time fixing it for my sake. I appreciate your response.
