### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by vikasTmz** [XavierXiao/Dreambooth-Stable-Diffusion#7]
Thanks for releasing this implementation.

GPU: Quadro P6000, 24GB RAM

I get "CUDA out of memory" on running both `scripts/stable_txt2img.py ` and `main.py`.

How much RAM did you consume in your experiments? And do you have suggestions on how to reduce/ de-allocate wasteful memory usage?

**Comment by XavierXiao** [comment]
Pretty huge, like 35+ Gbs. Maybe you can try original latent diffusion, instead of stable-diffusion. That will take less memory.

**Comment by viperyl** [comment]
Here is my testing gpu ram util rate 

![image](https://user-images.githubusercontent.com/45485217/189481670-bb801fd1-2583-476c-85ff-f8294e3f203b.png)

**Comment by vikasTmz** [comment]
Thanks!
