### ISSUE TITLE
Are data_root and reg_data_root the same? What should I put as data_root? 

### ISSUE THREAD

**Issue by asrlhhh** [XavierXiao/Dreambooth-Stable-Diffusion#8]
I saw the majority of the README file talking about regularization images. I guess those are used for fine-tuning. But what are the data_root used for? It seems to be from text inversion repo. Should I give the two the same folder path?

**Comment by MontaEllis** [comment]
same confusion...

**Comment by yuxu915** [comment]
> I saw the majority of the README file talking about regularization images. I guess those are used for fine-tuning. But what are the data_root used for? It seems to be from text inversion repo. Should I give the two the same folder path?

hi, same question, do you solve this problem?
